//product
export const FETCHING_DATAPRODUCT = 'FETCHING_DATAPRODUCT'
export const GET_LIMITDATAPRODUCT_SUCCESS = 'GET_LIMITDATAPRODUCT_SUCCESS'
export const GET_ALLDATAPRODUCT_SUCCESS = 'GET_ALLDATAPRODUCT_SUCCESS'
export const FETCHING_DATAPRODUCT_FAILURE = 'FETCHING_DATAPRODUCT_FAILURE'
// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART'
export const UPDATE_PRODUCT_TO_CART = 'UPDATE_PRODUCT_TO_CART'

//login
export const  REGISTER_REQUEST='USERS_REGISTER_REQUEST'
export const  REGISTER_SUCCESS= 'USERS_REGISTER_SUCCESS'
export const  REGISTER_FAILURE= 'USERS_REGISTER_FAILURE'

//register
export const  LOGIN_REQUEST= 'USERS_LOGIN_REQUEST'
export const  LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS'
export const  LOGIN_FAILURE= 'USERS_LOGIN_FAILURE'

// get All user
export const  GETALL_REQUEST= 'USERS_GETALL_REQUEST'
export const  GETALL_SUCCESS= 'USERS_GETALL_SUCCESS'
export const  GETALL_FAILURE= 'USERS_GETALL_FAILURE'

export const  LOGOUT= 'USERS_LOGOUT'

export const  SUCCESS= 'ALERT_SUCCESS'
export const  ERROR= 'ALERT_ERROR'
export const  CLEAR= 'ALERT_CLEAR'

// Detail
export const GETDETAIL_REQUEST = 'GETDETAIL_REQUEST'
export const  GETDETAIL_SUCCESS= 'GETDETAIL_SUCCESS'
export const  GETDETAIL_FAILURE= 'GETDETAIL_FAILURE'

// Mã Giảm Giá
export const GETMAGG_REQUEST = 'GETMAGG_REQUEST'
export const  GETMAGG_SUCCESS= 'GETMAGG_SUCCESS'
export const  GETMAGG_FAILURE= 'GETMAGG_FAILURE'

// Status trạng thái của componnet info
export const  STATUS_THONG_TIN_USER = 'STATUS_THONG_TIN_USER'
export const  STATUS_SAN_PHAM_YEU_THICH= 'STATUS_SAN_PHAM_YEU_THICH'
export const  STATUS_LICHSUGIAODICH= 'STATUS_LICHSUGIAODICH'
export const  STATUS_LICHSUDONHANG= 'STATUS_LICHSUDONHANG'
//State trạng thái view Thông tin User
export const  STATE_THONG_TIN_USER = 'STATE_THONG_TIN_USER'

//Gửi mail xác nhận
export const  SEND_EMAIL_USER = 'SEND_EMAIL_USER'


//Status trạng thái from Thông Tin USer
export const  SET_VIEW_EDIT_USER = 'SET_VIEW_EDIT_USER'

// get Limit
export const  ACT_PRODUCT_LIMIT = 'ACT_PRODUCT_LIMIT'