//product
export const FETCHING_DATAPRODUCT = 'FETCHING_DATAPRODUCT'
export const FETCHING_DATAPRODUCT_SUCCESS = 'FETCHING_DATAPRODUCT_SUCCESS'
export const FETCHING_DATAPRODUCT_FAILURE = 'FETCHING_DATAPRODUCT_FAILURE'
// Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART'
export const UPDATE_PRODUCT_TO_CART = 'UPDATE_PRODUCT_TO_CART'

//login
export const  REGISTER_REQUEST='USERS_REGISTER_REQUEST'
export const  REGISTER_SUCCESS= 'USERS_REGISTER_SUCCESS'
export const  REGISTER_FAILURE= 'USERS_REGISTER_FAILURE'

//register
export const  LOGIN_REQUEST= 'USERS_LOGIN_REQUEST'
export const  LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS'
export const  LOGIN_FAILURE= 'USERS_LOGIN_FAILURE'

// get All user
export const  GETALL_REQUEST= 'USERS_GETALL_REQUEST'
export const  GETALL_SUCCESS= 'USERS_GETALL_SUCCESS'
export const  GETALL_FAILURE= 'USERS_GETALL_FAILURE'

export const  LOGOUT= 'USERS_LOGOUT'

export const  SUCCESS= 'ALERT_SUCCESS'
export const  ERROR= 'ALERT_ERROR'
export const  CLEAR= 'ALERT_CLEAR'

// Detail
export const GETDETAIL_REQUEST = 'GETDETAIL_REQUEST'
export const  GETDETAIL_SUCCESS= 'GETDETAIL_SUCCESS'
export const  GETDETAIL_FAILURE= 'GETDETAIL_FAILURE'