//product
export const FETCHING_DATAPRODUCT = 'FETCHING_DATAPRODUCT'
export const GET_LIMITDATAPRODUCT_SUCCESS = 'GET_LIMITDATAPRODUCT_SUCCESS'
export const GET_ALLDATAPRODUCT_SUCCESS = 'GET_ALLDATAPRODUCT_SUCCESS'
export const FETCHING_DATAPRODUCT_FAILURE = 'FETCHING_DATAPRODUCT_FAILURE'

//Status trạng thái from Thông Tin USer
export const  SET_VIEW_EDIT_USER = 'SET_VIEW_EDIT_USER'

// get Limit
export const  ACT_PRODUCT_LIMIT = 'ACT_PRODUCT_LIMIT'

//Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART'
export const UPDATE_PRODUCT_TO_CART = 'UPDATE_PRODUCT_TO_CART'



//login
export const  REGISTER_REQUEST='USERS_REGISTER_REQUEST'
export const  REGISTER_SUCCESS= 'USERS_REGISTER_SUCCESS'
export const  REGISTER_FAILURE= 'USERS_REGISTER_FAILURE'

//register
export const  LOGIN_REQUEST= 'USERS_LOGIN_REQUEST'
export const  LOGIN_SUCCESS= 'USERS_LOGIN_SUCCESS'
export const  LOGIN_FAILURE= 'USERS_LOGIN_FAILURE'

//user
export const  GETALL_REQUEST= 'USERS_GETALL_REQUEST'
export const  GETALL_SUCCESS= 'USERS_GETALL_SUCCESS'
export const  GETALL_FAILURE= 'USERS_GETALL_FAILURE'

export const  LOGOUT= 'USERS_LOGOUT'

export const  SUCCESS= 'ALERT_SUCCESS'
export const  ERROR= 'ALERT_ERROR'
export const  CLEAR= 'ALERT_CLEAR'

export const CHECK_USER_ORDERS = 'CHECK_USER_ORDERS'

// Detail
export const GETDETAIL_REQUEST = 'GETDETAIL_REQUEST'
export const  GETDETAIL_SUCCESS= 'GETDETAIL_SUCCESS'
export const  GETDETAIL_FAILURE= 'GETDETAIL_FAILURE'

// Mã Giảm Giá
export const GETMAGG_REQUEST = 'GETMAGG_REQUEST'
export const  GETMAGG_SUCCESS= 'GETMAGG_SUCCESS'
export const  GETMAGG_FAILURE= 'GETMAGG_FAILURE'

//info
export const  STATUS_THONG_TIN_USER = 'STATUS_THONG_TIN_USER'
export const  STATUS_SAN_PHAM_YEU_THICH= 'STATUS_SAN_PHAM_YEU_THICH'
export const  STATUS_LICHSUGIAODICH= 'STATUS_LICHSUGIAODICH'
export const  STATUS_LICHSUDONHANG= 'STATUS_LICHSUDONHANG'

export const  STATE_THONG_TIN_USER = 'STATE_THONG_TIN_USER'

//Gửi mail xác nhận
export const  SEND_EMAIL_USER = 'SEND_EMAIL_USER'




// get orders theo khách hàng
export const  GET_ORDERS_REQUEST= 'GET_ORDERS_REQUEST'
export const  GET_ORDERS_SUCCESS= 'GET_ORDERS_SUCCESS'
export const  GET_ORDERS_FAILURE= 'GET_ORDERS_FAILURE'


export const  POST_ORDERS_REQUEST = 'POST_ORDERS_REQUEST'
export const  POST_ORDERS_SUCCESS= 'POST_ORDERS_SUCCESS'
export const  POST_ORDERS_FAILURE= 'POST_ORDERS_FAILURE'

export const  POST_ORDERDETALS_REQUEST = 'POST_ORDERDETALS_REQUEST'
export const  POST_ORDERDETALS_SUCCESS= 'POST_ORDERDETALS_SUCCESS'
export const  POST_ORDERDETALS_FAILURE= 'POST_ORDERDETALS_FAILURE'

// category
export const  GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'
export const  GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const  GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'

// search
export const  GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST'
export const  GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
export const  GET_SEARCH_FAILURE = 'GET_SEARCH_FAILURE'